name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: |
          echo "Current directory: $(pwd)"
          echo "Creating dist directory..."
          rm -rf dist
          mkdir -p dist
          echo "Copying website files..."
          cp -v website/* dist/
          echo "Copying images..."
          mkdir -p dist/images
          cp -v images/* dist/images/
          echo "Contents of dist directory:"
          ls -la dist/

      - name: Deploy to Pages repo
        uses: peaceiris/actions-gh-pages@v3
        with:
          external_repository: octxxiii/tab-timer-pages
          publish_branch: gh-pages
          publish_dir: ./dist
          personal_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          user_name: octxxiii
          user_email: octxxiii@users.noreply.github.com
          commit_message: "Deploy: ${{ github.event.head_commit.message }}"
